#!/usr/bin/env python3
import argparse
import os
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description="Convert local TTS audio with OpenVoice tone color conversion.")
    parser.add_argument("--source", required=True, help="Source speech WAV generated by Piper/eSpeak.")
    parser.add_argument("--reference", required=True, help="Reference speaker WAV.")
    parser.add_argument("--output", required=True, help="Converted output WAV.")
    parser.add_argument("--repo", required=True, help="Path to OpenVoice repository clone.")
    parser.add_argument("--checkpoint", required=True, help="Path to OpenVoice checkpoint directory, usually checkpoints_v2.")
    parser.add_argument("--language", default="EN_NEWEST", help="OpenVoice source speaker key.")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    checkpoint = Path(args.checkpoint).resolve()
    source = Path(args.source).resolve()
    reference = Path(args.reference).resolve()
    output = Path(args.output).resolve()
    if not repo.exists():
        raise SystemExit(f"OpenVoice repo is missing: {repo}")
    if not checkpoint.exists():
        raise SystemExit(f"OpenVoice checkpoint directory is missing: {checkpoint}")
    if not source.exists():
        raise SystemExit(f"Source audio is missing: {source}")
    if not reference.exists():
        raise SystemExit(f"Reference audio is missing: {reference}")

    sys.path.insert(0, str(repo))
    try:
        import torch
        from openvoice.api import ToneColorConverter
    except Exception as exc:
        raise SystemExit(f"OpenVoice import failed. Install OpenVoice dependencies in the selected Python env. Detail: {exc}")

    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    config = checkpoint / "converter" / "config.json"
    converter_checkpoint = checkpoint / "converter" / "checkpoint.pth"
    if not config.exists() or not converter_checkpoint.exists():
        raise SystemExit(f"OpenVoice converter checkpoint files are missing under: {checkpoint / 'converter'}")

    converter = ToneColorConverter(str(config), device=device)
    converter.load_ckpt(str(converter_checkpoint))
    source_ses = torch.load(str(checkpoint / "base_speakers" / "ses" / "en-newest.pth"), map_location=device)
    source_key = args.language
    if isinstance(source_ses, dict):
        source_se = source_ses.get(source_key) or source_ses.get("EN_NEWEST") or next(iter(source_ses.values()))
    else:
        source_se = source_ses
    target_se = converter.extract_se([str(reference)])
    output.parent.mkdir(parents=True, exist_ok=True)
    converter.convert(
        audio_src_path=str(source),
        src_se=source_se,
        tgt_se=target_se,
        output_path=str(output),
        message="@NicheFoundry"
    )


if __name__ == "__main__":
    main()
